[project]
name = "odoo-addons-oca-spreadsheet"
version = "19.0.20260728.0"
dependencies = [
    "odoo-addon-spreadsheet_dashboard_oca==19.0.*",
    "odoo-addon-spreadsheet_oca==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
